language: javascript
env:
  global:
  - TRAVIS_LAUNCHES_SAUCE_CONNECT=true
  - secure: lTlOUWwrtyeN6HqCHNaqaQQF1aBx50W2F4r/KEg/nZcV/QDJAa0wqAbs11+4sEUW5FpA56zieha3G4fG+Iv/3IDAXahHC7LRYB06hK3l0PvaApzPDWq8JQpLs0KS+GRU/kwHA8vemn4KfcI1Ue7WNfCi1vp8V46miA2Gjdjf2e4=#SAUCE_USERNAME=smcgregor (smcgregor/privly-applications)
  - secure: at4ygn2fOHba8vPRQi1ZEBIf+agBupMVtkY5ChpeZhcY3p0tgKV9PhQ5IxWLL6TxN86I2VgrC6W54y6kKGQ6TVz7j/z1P3z2DD7Ktb/WqwgLYY4ErSMCSXmOHVp5ckaVNuZL0zf9E0LEIM4MqiuWiqtEN1C+ChebsVQLLCUqeIo=#SAUCE_ACCESS_KEY=********-****-****-****-************ (smcgregor/privly-applications)
script:
- cd test
- "./run_each.sh karma.conf-ci.js"
before_script:
- "cd test/ && npm install -g karma-cli && npm install && cd .."
addons:
  sauce_connect: true
