language: javascript
env:
  global:
  - TRAVIS_LAUNCHES_SAUCE_CONNECT=true # Tell the karma file that it does not need to launch Sauce connect
script:
- cd test
- "./run_each.sh karma.conf-ci.js"
before_script:
- "cd test/ && npm install -g karma-cli && npm install && cd .."
addons:
  sauce_connect:
    username: smcgregor
    access_key:
      secure: "aQMkB5holloDOeszOJ4JON0zRH2TMl+mU1fqUpOO4cvI4iLAHxfmXg8aohQVcxYtjtWodXMDxFIpTuemkyG014LD9Z+2oMvP7915Y4JR/VNE0H2cqj/nF3CP1V8U7Rb6lWAFdYdz/aq4OnqakETQsse5LlYHcVYSg/6x5/o0UkA="